Awesome books: with ES6
Yonashenok/Awesome-Books-ES6 pull request #1
Opened 2023-06-12 18:27 UTC by Yonashenok

## what I did 
* Make sure no linter error
* Created module directory and files
* used ES6 syntax
* Create a separate file for each functionality
* Display the current date below the navigation bar
* use library Luxon

2023-06-12 20:36 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Yonashenok, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-12 20:36 UTC, Qoosim commented on modules/formHandler.js
> +};
- [ ] It is required to ensure that application is working as expected. It should be possible to add and remove books from the list. Below is the screenshot of what I got while trying to add book to the list.

### Your App
![addBook](https://github.com/Yonashenok/Awesome-Books-ES6/assets/26597432/83de96c6-f3b3-4037-a190-7febe62a06bc)

2023-06-12 20:36 UTC, Qoosim commented on modules/timeDate.js
> +export default setTimeDate;
- [ ] It is required the current date is displayed below the navigation bar. Kindly fix that.

### Your Website
![date](https://github.com/Yonashenok/Awesome-Books-ES6/assets/26597432/37b247bc-e836-44c8-a724-25eefa6176ad)

### Project Requirement
![project-rqt](https://github.com/Yonashenok/Awesome-Books-ES6/assets/26597432/d8cf8492-7681-4e47-ac3c-345669e6e897)

2023-06-13 13:34 UTC, Strangeal requested changes
Hi @Yonashenok, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 13:34 UTC, Strangeal commented on modules/formHandler.js
> +export default formSubmitHandler;
- [ ]  As suggested by the previous reviewer, kindly ensure that the application is working as expected. It should be possible to add and remove books from the list. Below is the screenshot of what I got while trying to add book to the list.
<img src="https://user-images.githubusercontent.com/26597432/245271144-83de96c6-f3b3-4037-a190-7febe62a06bc.png" />

2023-06-13 13:34 UTC, Strangeal commented on modules/timeDate.js
> +export default setTimeDate;
- [ ] As suggested by the previous and also specified in the project requirements, Please display the `date` below the navigation bar. This way users can track their time for adding books to your app to create a good user experience.

2023-06-13 14:11 UTC, Yonashenok commented on modules/formHandler.js
> +export default formSubmitHandler;
# time and Date work fine  in mine

![image](https://github.com/Yonashenok/Awesome-Books-ES6/assets/99332080/2f4b5d0c-e6c4-4425-bb78-0d0fd3071846)

2023-06-13 14:58 UTC, medaminedev66 commented
Hello @Yonashenok👋,

_This is an additional review as a result of the second opinion request._

I confirm that your web app functions as expected, allowing users to successfully add and remove books. Additionally, the date is correctly displayed below the navbar. Good job! 👏 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

2023-06-13 15:37 UTC, Rustamxon7 approved these changes
Hi @Yonashenok, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯
3. Well-implemented code 👍 

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 07:33 UTC, merged